#!/bin/bash
umask 177

if [ "$1" == "" ]; then
  echo "  Usage: $0 <host_ip> [port] [timeout]"
  exit
fi

host=`echo $1 | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}'`
if [ $? -ne 0 ]; then
  echo "\"$1\" in not a valid IPv4"
  exit 1
fi

port=`echo $2 | egrep -o '[0-9]{2,5}' || echo 5060`
timeout=`echo $3 | egrep -o '[0-9]{1,5}' || echo 300`

(sleep ${timeout}s && pkill -P $$) &
echo "*** host $host and proto udp and port $port ***"
stdbuf -oL tcpdump -i any -s 65535 -w - host $host and proto \\udp and port $port | stdbuf -oL strings |\
 awk --re-interval '/^.?([[:upper:]]{3,})/{gsub(/[[:upper:]]{3,}/,"\033[1;31m&\033[1;000m")};/^CSeq:/{gsub(/^CSeq:/,"\033[1;36m&\033[1;000m")}{print $0}'
