#!/bin/sh
umask 133
# Manage sounds behind nginx

function moh() {
  echo 1
  MOH=`echo "${1}" | sed -r 's|^/var/lib/asterisk/MOH||' | cut -d '/' -f 2`
  [ "${MOH}" == "" ] && return
  [ -f "/etc/asterisk/moh/${MOH}.conf" ] && return

  cat <<EOF > /etc/asterisk/moh/${MOH}.conf
[${MOH}]
mode=files
directory=/var/lib/asterisk/MOH/${MOH}
sort=alpha
EOF
  asterisk -rx 'moh reload' > /dev/null 2>&1
}

if [ "$1" == "cp" ]; then
  f=`readlink -f "${4}" | egrep -q '^/var/lib/asterisk/(sounds|MOH)'`
  [ $? -ne 0 ] && exit

  mkdir "${4}" 2>/dev/null && chmod 755 "${4}"

  f=`readlink -f "${2}" | egrep "^${4}|^/tmp/"`
  [ $? -ne 0 ] && exit

  f=`readlink -f "${3}" | egrep "^${4}"`
  [ $? -ne 0 ] && exit

  f=`echo "${3}" | egrep '\.(alaw|raw)$'`
  if [ $? -eq 0 ]; then
    out=`echo "${3}" | sed -r 's/\.[^.]+$/\.alaw/'`
    cp "${2}" "${out}"
  else
    out=`echo "${3}" | sed -r 's/\.[^.]+$/\.wav/'`
    f=`file "${2}" | grep 'RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 8000 Hz'`
    if [ $? -eq 0 ]; then
      cp "${2}" "${out}"
    else
      ffmpeg -i "${2}" -ac 1 -ar 8000 -ab 128k -b 16 -y "${out}" > /dev/null 2>&1
    fi
  fi

  if [ $? -eq 0 ]; then
    chmod 644 "${out}"
    echo 'OK'
    readlink -f "${3}" | egrep -q '^/var/lib/asterisk/MOH/.+' && moh "${3}"
  fi
fi

if [ "$1" == "mv" ]; then
  f=`readlink -f "${4}" | egrep '^/var/lib/asterisk/(sounds|MOH)'`
  [ $? -ne 0 ] && exit

  mkdir "${4}" 2>/dev/null && chmod 755 "${4}"

  f=`readlink -f "${2}" | egrep "^${4}|^/tmp/"`
  [ $? -ne 0 ] && exit

  f=`readlink -f "${3}" | egrep "^${4}"`
  [ $? -ne 0 ] && exit

  mv "${2}" "${3}"
  if [ $? -eq 0 ]; then
    echo 'OK'
    readlink -f "${3}" | egrep -q '^/var/lib/asterisk/MOH/.+' && moh "${3}"
  fi
fi

if [ "$1" == "rm" ]; then
  f=`readlink -f "${3}" | egrep '^/var/lib/asterisk/(sounds|MOH)'`
  [ $? -ne 0 ] && exit

  f=`readlink -f "${2}" | egrep "^${3}"`
  [ $? -ne 0 ] && exit

  rm -f "${2}"
  if [ $? -eq 0 ]; then
    echo 'OK'
  fi
fi

if [ "$1" == "rmdir" ]; then
  f=`readlink -f "${3}" | egrep '^/var/lib/asterisk/(sounds|MOH)'`
  [ $? -ne 0 ] && exit

  f=`readlink -f "${2}" | egrep "^${3}"`
  [ $? -ne 0 ] && exit

  rmdir "${2}"
  if [ $? -eq 0 ]; then
    echo 'OK'
  fi
fi

if [ "$1" == "mkdir" ]; then
  f=`readlink -f "${3}" | egrep '^/var/lib/asterisk/(sounds|MOH)'`
  [ $? -ne 0 ] && exit

  f=`readlink -f "${2}" | egrep "^${3}"`
  [ $? -ne 0 ] && exit

  mkdir -p "${2}"
  if [ $? -eq 0 ]; then
    chmod 755 "${2}"
    echo 'OK'
  fi
fi

if [ "$1" == "touch" ]; then
  f=`readlink -f "${3}" | egrep '^/var/lib/asterisk/(sounds|MOH)'`
  [ $? -ne 0 ] && exit

  mkdir "${3}" 2>/dev/null && chmod 755 "${3}"

  f=`readlink -f "${2}" | egrep "^${3}"`
  [ $? -ne 0 ] && exit

  touch "${2}"
  if [ $? -eq 0 ]; then
    chmod 644 "${2}"
    echo 'OK'
    readlink -f "${2}" | egrep -q '^/var/lib/asterisk/MOH/.+' && moh "${2}"
  fi
fi
